# Generated by Django 5.2 on 2025-04-14 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200)),
                ('model_year', models.IntegerField(blank=True, null=True)),
                ('plate', models.CharField(blank=True, max_length=7, null=True, unique=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cars/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Disponível'), ('sold', 'Vendido')], default='available', max_length=10)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars_brand', to='cars.brand')),
            ],
        ),
    ]
